In [2]:
import numpy as np

x = np.array([1,2,3,4,5])#一位数组

In [3]:
print(x)
print(type(x))#<class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#numpy的数组有些很实用的属性 dtype
x.dtype
#注意 dtype和数组本身的数据类型不同
#dtype('int64') dtype告诉我们 ndarray存放的数有符号的64位整数

#可以处理的类型比py多 是numpy的一大优势

dtype('int64')

In [9]:
#shape  返回一个由n个正整数组成的元组
print(x.shape) #(5,） 说明数组每个维度大小中 其中n为数组的维度

#二维的 
y1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12,13]])
y2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(y1.shape)#(4,) array里面的元素全部都是数组 并且每个数组长度一样 才会是二维
print(y2.shape)#(4, 3) 有两个元素 所以y有两个维度

print(y1.size)
print(y2.size)


(5,)
(4,)
(4, 3)
4
12


In [27]:
#如果array里面存着字符串
str_arr = np.array(['Hello','World','abcabc'])
print('dtype',str_arr.dtype)#dtype <U76这里的6指的数组里面 最长的字符或者数字的长度

#会把数字转成成数字字符串
mix_arr = np.array([2,111,'helloa','aaassssss'])
print('dtype',mix_arr.dtype)#21个字符组成的unicode

dtype <U6
dtype <U21


In [31]:
#如果出现整数和浮点数  会全部转成浮点数 🔼转型
float_int_arr = np.array([1,2.5,4,6])
print(float_int_arr,float_int_arr.dtype)

#也可以强行向下转型 全部转变成整型
arr2 = np.array([1,2.9,3,5],dtype=np.int64)
print(arr2,arr2.dtype)

[1.  2.5 4.  6. ] float64
[1 2 3 5] int64


# numpy使用内置函数创建ndarray

In [40]:
#numpy不仅可以传入list转化成ndarray 也能使用内置函数创建
x0 = np.zeros((3,4))#创建二维数组 长度为3  每个元素是长度为4的list
#填充0
print('np.zeros')
print(x0)#填充0
#默认每一项是小数 可以强行转换成整数

#填充1
x1 = np.ones((4,5),dtype=np.int64)
print('np.ones')
print(x1)

#填充其他
x5 = np.full((4,3),5)
print('np.full')
print(x5)

#线性代数有一种基础数组叫做单位矩阵(identity matrix) 
#就是指横纵排列的二维数组

x_m = np.eye(6) #单位矩阵是方形的 只能接收一个单精度整数参数
#得到一个6x6的单位矩阵
print('np.eye')
print(x_m)#左上角第一个 到右下角最后一个 对角线位置的值为1 其他位置为0

#还能使用diag 接收一个数组 数组的长度为L 则得到一个LXL的矩阵
x_d = np.diag([10,22,35,76])
print('np.diag')
print(x_d)


np.zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
np.ones
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
np.full
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
np.eye
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
np.diag
[[10  0  0  0]
 [ 0 22  0  0]
 [ 0  0 35  0]
 [ 0  0  0 76]]


In [45]:
#numpy可以生成特定数值范围的数组 arrange 创建给定区间的等差数组
a1 = np.arange(8)#a1 = [0 1 2 3 4 5 6 7]
a2 = np.arange(1,8)#a2 =  [1 2 3 4 5 6 7]
x = np.arange(1,14,3)#x =  [ 1  4  7 10 13] 
#arange 的第三个参数给等差的值 也是整数 也可以是小数 ，但不推荐用arange
#使用linspace

# We print the ndarray
print('a1 =',a1)
print('x = ', x)
print('a2 = ',a2)

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

print('----linspace----')#至少要两个参数 没有
x_lin = np.linspace(0,25,10)
x_lin1 = np.linspace(0,25,10,endpoint = False)
#因为从0 开始 25结束  起始和终止都在数组里面 可以不包含终止值
#[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889 16.66666667 19.44444444 22.22222222 25.        ]

print(x_lin)
print(x_lin1)



a1 = [0 1 2 3 4 5 6 7]
x =  [ 1  4  7 10 13]
a2 =  [1 2 3 4 5 6 7]
x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64
----linspace----
[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [49]:
# linspace和arange不仅可以创建一维数组 还能创建二维
#结合reshape
x1 = np.reshape(np.arange(12),(4,3))
print(x1)
'''
但是 不能改变成x*y不等于 原来一位数组的总长度
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
 
 numpy函数可以连起来写 链式操作
'''

x_lin2 = np.linspace(0,50,10,endpoint = False).reshape(5,2)
print(x_lin2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [62]:
#在机器学习中经常有需要创建随机矩阵的时候
#比如初始化神经网络的权重
#np.random 访问该模块 再访问里面的random函数
x_random = np.random.random((3,4))
print(x_random)#都是随机的小数 0-1

#3-9的随机数
x_random_int = np.random.randint(3,10,(3,4))
print(x_random_int)

#平均值0 标准差为0.1的正态分布
x_normal = np.random.normal(0,0.1,(1000,1000))
print('平均值',x_normal.mean());
print('标准差',x_normal.std());
print('最小值',x_normal.min());
print('最大值',x_normal.max());
#最小值加最大值等于平均值0
#正数和负数也差不多

[[0.00536209 0.33995116 0.24372392 0.79636383]
 [0.26382324 0.23207582 0.5268261  0.94536737]
 [0.93105786 0.03092731 0.4572357  0.37395795]]
[[8 7 6 9]
 [9 4 5 5]
 [8 3 3 7]]
平均值 0.00013516993505191064
标准差 0.09986853716858174
最小值 -0.49018355229414123
最大值 0.4492170387131513


# 访问和删除 ndarray 中的元素及向其中插入元素

In [64]:
#numpy数组是可变的(mutable) numpy数组有很多种切片方式
x = np.array([1,2,3,4,5])
#修改ndarray里面某个值
x[3] = 28
print(x)

x2 = np.arange(1,10).reshape(3,3)

print(x2)
#两种查找二维数组中某个值的方法
print(x2[2,1])
print(x2[2][0])



[ 1  2  3 28  5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
7


In [76]:
y1 = np.arange(1,10).reshape(3,3)
print(np.delete(y1,0,axis=1))#删掉一纵行 每个List里面的第一个
print(np.delete(y1,0,axis=0))#删掉一横行

new_y1 = np.append(y1,[[20,30,40]],axis=0)
print(new_y1)

y2 = np.arange(1,10)
new_y2 = np.append(y2,[11,12])
print(new_y2)

[[2 3]
 [5 6]
 [8 9]]
[[4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [20 30 40]]
[ 1  2  3  4  5  6  7  8  9 11 12]


In [79]:
#append是在尾部追加一个 中间插入则是insert
x = np.array([1,2,5,6,9])
#第二个参数是插到原数组哪一个的后面 从1开始数的
x = np.insert(x,3,[22,33])
print(x)


#二维数组的插入
y = np.array([[1,2,3],[7,8,9]])
w = np.insert(y,1,[4,5,6],axis=0)
v = np.insert(y,1,123,axis=1)

print('y:',y)
print('w:',w)
print('v:',v)


#py可以用vstack进行垂直堆叠 hstack进行水平堆叠



[ 1  2  5 22 33  6  9]
y: [[1 2 3]
 [7 8 9]]
w: [[1 2 3]
 [4 5 6]
 [7 8 9]]
v: [[  1 123   2   3]
 [  7 123   8   9]]


In [80]:
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]


# ndarray的切片 

In [82]:
'''
    常见三种切片
    [start:end]
    [start:]
    [:end]
'''

X = np.arange(20).reshape(4, 5)
Z = X[1:4,2:5]
print(X)#1:4 找到 从下标为1找到正数第四个 
print('Z = \n', Z)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [83]:
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
Z = X[1:4,2:5]

# We print Z
print()
print('Z = \n', Z)
print()

#如果修改z里面某个值 原数组x里面也会被修改
# We change the last element in Z to 555
Z[2,2] = 555

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


X = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]



In [91]:
#使用copy可以避免原数组被修改
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])

#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

# We change the last element in Z to 555
Z[2,2] = 555

# We change the last element in W to 444
W[2,2] = 444

# We print X
print()
print('X = \n', X)

# We print Z
print()
print('Z = \n', Z)

# We print W
print()
print('W = \n', W)
#diag可以去到对角线的值

print('diag k=0:',np.diag(W,k=0))

print('diag k=1:',np.diag(W,k=1))

print('diag k=-1:',np.diag(W,k=-1))


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

W = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]
diag k=0: [  7  13 444]
diag k=1: [ 8 14]
diag k=-1: [12 18]


In [92]:
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
#unique 找出独一无二的值 返回一个数组
print(np.unique(X))

[1 2 3 5 8]


# 布尔型索引、集合运算和排序

In [98]:
#如果有一个10000X10000的随机整数数组 1-15000之间
#只要小于20
x = np.arange(25).reshape(5,5)
print(x[x > 10])#返回一个一位数组 这就是布尔表达式

#只能是&  &&和and都是错误
print(x[(x > 8) & (x < 14)])

#可以将在这个取值范围的值全部改变
x[(x > 8) & (x < 14)] = -1
print(x)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[ 9 10 11 12 13]
[[ 0  1  2  3  4]
 [ 5  6  7  8 -1]
 [-1 -1 -1 -1 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [99]:
# numpy还能进行集合运算
#很方便我们比较两个numpy数组
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
print(np.intersect1d(x,y))#查找x中和y中都有的元素
#[2 4]
print(np.setdiff1d(x,y))#x中的元素 如果在y中出现 则删除掉这个元素
#[1 3 5]
print(np.union1d(x,y))#列出x,y 所有元素

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [107]:
#排序 
x = np.random.randint(1,11,size=(10,))#一维数组
print(x)
print(np.sort(x))#排序操作不会删除重复元素
print(np.sort(np.unique(x)))

#二维数组排序 横向或者纵向
x = np.random.randint(1,11,size=(5,6))
print(x)
print('纵向排列------')
print(np.sort(x,axis=0))
print('横向排列------')
print(np.sort(x,axis=1))

[8 7 7 4 5 8 2 3 1 2]
[1 2 2 3 4 5 7 7 8 8]
[1 2 3 4 5 7 8]
[[ 2 10  7  2  3 10]
 [ 9  9 10  7  9  9]
 [ 8  9  7  4  4  5]
 [ 9 10  9  4  4  1]
 [ 5 10  1  1  4  3]]
------
[[ 2  9  1  1  3  1]
 [ 5  9  7  2  4  3]
 [ 8 10  7  4  4  5]
 [ 9 10  9  4  4  9]
 [ 9 10 10  7  9 10]]
------
[[ 2  2  3  7 10 10]
 [ 7  9  9  9  9 10]
 [ 4  4  5  7  8  9]
 [ 1  4  4  9  9 10]
 [ 1  1  3  4  5 10]]


# 算术运算和广播

In [125]:
#NumPy 允许对 ndarray 执行元素级运算以及矩阵运算。
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(x+y)
#每个下标对应的相加
print(np.add(x,y))
print('相减')
print(np.subtract(x,y))
print('相乘')
print(np.multiply(x,y))
print('相除')
print(np.divide(x,y))
#为了完成这些运算 numpy会用一种广播的机制
#numpy对应不同形状的数组进行元素算术运算的处理过程

print(np.sqrt(x))#求每个值的开方 
print(np.exp(x))#求e的几次方 有值绝对 e等于2.71828183
print(np.power(x,2))#得到平方


#mean求平均值
x = np.arange(1,5).reshape(2,2)
print('二维数组所有数的平均值',x.mean())
print('二维数组所有纵轴的平均值',np.mean(x,axis=0))
print('二维数组所有横轴的平均值',x.mean(axis=1))
print('二维数组所有数的标准差',np.std(x))
print('二维数组所有数的中位数',np.median(x))



[ 6  8 10 12]
[ 6  8 10 12]
相减
[-4 -4 -4 -4]
相乘
[ 5 12 21 32]
相除
[0.2        0.33333333 0.42857143 0.5       ]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 1  4  9 16]
二维数组所有数的平均值 2.5
二维数组所有纵轴的平均值 [2. 3.]
二维数组所有横轴的平均值 [1.5 3.5]
二维数组所有数的标准差 1.118033988749895
二维数组所有数的中位数 2.5


In [124]:
#每个值加减乘除
print(x+3)

x = np.arange(3).reshape(1,3)
print(x)
y = np.arange(9).reshape(3,3)
print(y+x)


[[3]
 [4]
 [5]]
[[0 1 2]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [138]:
x = np.arange(20).reshape(4,5)
print(x)
print(np.mean(x,axis=0))
print(np.std(x,axis=0))
print(x - np.mean(x,axis=0) )
print((x - np.mean(x,axis=0)) / np.std(x,axis=0)  )

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 7.5  8.5  9.5 10.5 11.5]
[5.59016994 5.59016994 5.59016994 5.59016994 5.59016994]
[[-7.5 -7.5 -7.5 -7.5 -7.5]
 [-2.5 -2.5 -2.5 -2.5 -2.5]
 [ 2.5  2.5  2.5  2.5  2.5]
 [ 7.5  7.5  7.5  7.5  7.5]]
[[-1.34164079 -1.34164079 -1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079  1.34164079  1.34164079]]
